[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.156.0"

[context.production]
  command = "hugo --gc --minify --baseURL https://jcosta.dev/"

[context.deploy-preview]
  command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"
